import React, { createContext, useState, useContext } from 'react';

export const translations = {
  en: {
    singleplayer: "Singleplayer",
    playVsBot: "Start Game",
    onlineMultiplayer: "Online Multiplayer",
    matchId: "Match ID",
    enterRoomId: "Enter Room ID",
    logo: "RONDA",
    host: "Host",
    join: "Join",
    opponent: "Opponent",
    you: "You",
    yourTurn: "(Your Turn)",
    cards: "Cards:",
    tableEmpty: "Table is empty",
    gameOver: "Game Over!",
    itsADraw: "It's a draw!",
    youWon: "You won!",
    opponentWon: "Opponent won!",
    playAgain: "Play Again",
    mainMenu: "Main Menu",
    cardsRemaining: "Cards remaining",

    roundOver: "Round Over!",
    totalGames: "Total Wins",
    shareText: "Join my Ronda game!",
    linkCopied: "Link copied to clipboard!",
    donateBtn: "Buy us a Mint Tea",
    donateMsg: "Enjoying the game? Buy the dev team a cup of Mint Tea!",
    connecting: "Connecting...",
    connectingDetail: "Waiting for the game server to respond.",
    roomOccupied: "Room is occupied, please choose another name.",
    roomFull: "Room is full.",
    backToMenu: "Back to Menu",
    shareLink: "Copy Invitation Link",
    rulesBtn: "How to Play",
    contactUs: "Contact us",
    rulesTitle: "How to Play Ronda",
    rulesIntro: "Ronda is a popular card game played with a 40-card deck. The goal is to capture cards and accumulate the most points.",
    rulesGameplay: "Gameplay: Players receive 3 cards per round. Play one card per turn. If your card matches a card on the table, you capture it along with any following cards in sequence.",
    rulesPoints: "Scoring: The player with the most captured cards wins the round. Special moves give immediate bonus points:",
    rulesMissa: "• Missa: Clearing all cards from the table (+1 point).",
    rulesDerba: "• Derba: Capturing the exact card the opponent just played (+1 point).",
    rulesRonda: "• Ronda: Having a pair in hand after cards are dealt (+1 point).",
    rulesTringa: "• Tringa: Having three of a kind in hand (+5 points).",
    rulesSpecialMovesTitle: "Special Events",
    rulesClash: "• Clash of Rondas: If both players have Ronda, the higher pair wins all points (+2).",
    rulesTringaVsRonda: "• Tringa vs Ronda: Tringa beats Ronda and wins all points (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa: If both players have Tringa, the higher rank wins (+10 points).",
    rulesCounterAttack: "• Counter Attack: Countering a Derba (Taawida) (+5 points).",
    rulesUltimateAttack: "• Ultimate Attack: Countering a Counter Attack (+10 points).",
    rulesFinalFail: "• Final Fail: Missing the last card gives +5 points to the opponent.",
    rulesKingFinish: "• King Finish: Capturing with a King as the very last card of the game (+5 points).",
    rulesAsFinish: "• As Finish: Capturing with an Ace as the very last card gives +5 points to the opponent.",
    announcements: {
      ronda: "Ronda! (+1) - {name}",
      tringa: "Tringa! (+5) - {name}",
      missa: "Missa! (+1) - {name}",
      derba: "Derba! (+1) - {name}",
      taawida: "Taawida! - {name}",
      counterAttackTitle: "Counter Attack",
      counterAttackDesc: "Derba is countered",
      ultimateCounterTitle: "Ultimate Counter",
      ultimateCounterDesc: "Ultimate Counter-Attack",
      clash: "Clash! Both have Ronda!",
      clashWon: "Clash won with {type}! (+{pts}) - {name}",
      clashDraw: "Clash Draw!",
      kingFinish: "👑 King Finish! (+5)",
      tringaWins: "Tringa beats Ronda! (+6) - {name}",
      finalFailTitle: "Final Fail",
      finalFailDesc: "Missed the last card! (+5 for opponent)",
      asFinishTitle: "As Finish",
      asFinishDesc: "Captured with Ace! (+5 for opponent)"
    }
  },
  fr: {
    singleplayer: "Un Joueur",
    playVsBot: "Commencer le jeu",
    onlineMultiplayer: "Multijoueur en Ligne",
    matchId: "ID du Match",
    enterRoomId: "Entrer l'ID",
    logo: "RONDA",
    host: "Créer",
    join: "Rejoindre",
    opponent: "Adversaire",
    you: "Vous",
    yourTurn: "(À ton tour)",
    cards: "Cartes :",
    tableEmpty: "La table est vide",
    gameOver: "Partie Terminée !",
    itsADraw: "Égalité !",
    youWon: "Vous avez gagné !",
    opponentWon: "L'adversaire a gagné !",
    playAgain: "Rejouer",
    mainMenu: "Menu Principal",
    cardsRemaining: "Cartes restantes",

    roundOver: "Manche Terminée !",
    totalGames: "Victoires Totales",
    shareText: "Rejoins ma partie de Ronda !",
    linkCopied: "Lien copié dans le presse-papiers !",
    donateBtn: "Offrez-nous un Thé à la Menthe",
    donateMsg: "Vous aimez le jeu ? Offrez un thé à l'équipe de développement !",
    connecting: "Connexion...",
    connectingDetail: "En attente d'une réponse du serveur de jeu.",
    roomOccupied: "La salle est occupée, veuillez choisir un autre nom.",
    roomFull: "La salle est pleine.",
    backToMenu: "Retour au Menu",
    shareLink: "Copier le lien d'invitation",
    rulesBtn: "Règles du jeu",
    contactUs: "Nous contacter",
    rulesTitle: "Comment jouer à Ronda",
    rulesIntro: "Ronda est un jeu de cartes populaire joué avec un jeu de 40 cartes. Le but est de capturer des cartes et d'accumuler le plus de points.",
    rulesGameplay: "Déroulement : Les joueurs reçoivent 3 cartes par manche. Jouez une carte par tour. Si votre carte correspond à une carte sur la table, vous la capturez avec les cartes suivantes en séquence.",
    rulesPoints: "Points : Le joueur avec le plus de cartes capturées gagne. Les coups spéciaux donnent des points bonus immédiats :",
    rulesMissa: "• Missa : Vider toutes les cartes de la table (+1 point).",
    rulesDerba: "• Derba : Capturer la carte exacte que l'adversaire vient de jouer (+1 point).",
    rulesRonda: "• Ronda : Avoir une paire en main après la distribution (+1 point).",
    rulesTringa: "• Tringa : Avoir un brelan en main (+5 points).",
    rulesSpecialMovesTitle: "Événements Spéciaux",
    rulesClash: "• Clash de Rondas : Si les deux joueurs ont Ronda, la paire la plus haute gagne (+2 points).",
    rulesTringaVsRonda: "• Tringa vs Ronda : Tringa bat Ronda et gagne tous les points (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa : Si les deux joueurs ont Tringa, le plus haut gagne (+10 points).",
    rulesCounterAttack: "• Contre-Attaque : Contrer une Derba (Taawida) (+5 points).",
    rulesUltimateAttack: "• Attaque Ultime : Contrer une Contre-Attaque (+10 points).",
    rulesFinalFail: "• Échec Final : Rater la dernière carte donne +5 points à l'adversaire.",
    rulesKingFinish: "• King Finish : Faire un pli avec un Roi comme toute dernière carte du jeu (+5 points).",
    rulesAsFinish: "• As Finish : Faire un pli avec un As comme toute dernière carte donne +5 points à l'adversaire.",
    announcements: {
      ronda: "Ronda ! (+1) - {name}",
      tringa: "Tringa ! (+5) - {name}",
      missa: "Missa ! (+1) - {name}",
      derba: "Derba ! (+1) - {name}",
      taawida: "Taawida ! - {name}",
      counterAttackTitle: "Contre-Attaque",
      counterAttackDesc: "Derba est contrée",
      ultimateCounterTitle: "Contre Ultime",
      ultimateCounterDesc: "Contre-attaque ultime",
      clash: "Clash ! Les deux ont Ronda !",
      clashWon: "Clash gagné avec {type} ! (+{pts}) - {name}",
      clashDraw: "Clash : Égalité !",
      kingFinish: "👑 King Finish ! (+5)",
      tringaWins: "La Tringa bat la Ronda ! (+6) - {name}",
      finalFailTitle: "Échec Final",
      finalFailDesc: "Dernière carte manquée ! (+5 pour l'adversaire)",
      asFinishTitle: "As Finish",
      asFinishDesc: "A gagné avec l'As ! (+5 pour l'adversaire)"
    }
  },
  de: {
    singleplayer: "Einzelspieler",
    playVsBot: "Spiel starten",
    onlineMultiplayer: "Online-Mehrspieler",
    matchId: "Match-ID",
    enterRoomId: "Raum-ID eingeben",
    logo: "RONDA",
    host: "Erstellen",
    join: "Beitreten",
    opponent: "Gegner",
    you: "Du",
    yourTurn: "(Du bist dran)",
    cards: "Karten:",
    tableEmpty: "Der Tisch ist leer",
    gameOver: "Spiel vorbei!",
    itsADraw: "Unentschieden!",
    youWon: "Du hast gewonnen!",
    opponentWon: "Der Gegner hat gewonnen!",
    playAgain: "Nochmal spielen",
    mainMenu: "Hauptmenü",
    cardsRemaining: "Verbleibende Karten",

    roundOver: "Runde vorbei!",
    totalGames: "Gesamtsiege",
    shareText: "Tritt meinem Ronda-Spiel bei!",
    linkCopied: "Link in die Zwischenablage kopiert!",
    donateBtn: "Spendier uns einen Minztee",
    donateMsg: "Gefällt dir das Spiel? Spendier dem Team einen Minztee!",
    connecting: "Verbindung wird hergestellt...",
    connectingDetail: "Warten auf Antwort vom Spielserver.",
    roomOccupied: "Raum ist besetzt, bitte wähle einen anderen Namen.",
    roomFull: "Raum ist voll.",
    backToMenu: "Zurück zum Menü",
    shareLink: "Einladungslink kopieren",
    rulesBtn: "Spielregeln",
    contactUs: "Kontaktiere uns",
    rulesTitle: "Wie man Ronda spielt",
    rulesIntro: "Ronda ist ein beliebtes Kartenspiel mit 40 Karten. Das Ziel ist es, Karten zu sammeln und die meisten Punkte zu erzielen.",
    rulesGameplay: "Spielablauf: Jeder Spieler erhält 3 Karten pro Runde. Spiele eine Karte pro Zug. Wenn deine Karte mit einer Karte auf dem Tisch übereinstimmt, nimmst du sie sowie alle nachfolgenden Karten in der Reihe.",
    rulesPoints: "Punkte: Der Spieler mit den meisten Karten gewinnt die Runde. Spezielle Züge geben sofortige Bonuspunkte:",
    rulesMissa: "• Missa: Alle Karten vom Tisch abräumen (+1 Punkt).",
    rulesDerba: "• Derba: Genau die Karte nehmen, die der Gegner gerade gespielt hat (+1 Punkt).",
    rulesRonda: "• Ronda: Ein Paar auf der Hand haben, nachdem die Karten ausgeteilt wurden (+1 Punkt).",
    rulesTringa: "• Tringa: Drei gleiche Karten auf der Hand haben (+5 Punkte).",
    rulesSpecialMovesTitle: "Besondere Ereignisse",
    rulesClash: "• Clash of Rondas: Wenn beide Spieler Ronda haben, gewinnt das höhere Paar (+2 Punkte).",
    rulesTringaVsRonda: "• Tringa vs Ronda: Tringa schlägt Ronda und gewinnt alle Punkte (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa: Wenn beide Spieler Tringa haben, gewinnt der höhere Rang (+10 Punkte).",
    rulesCounterAttack: "• Gegenangriff: Kontern einer Derba (Taawida) (+5 Punkte).",
    rulesUltimateAttack: "• Ultimativer Konter: Kontern eines Gegenangriffs (+10 Punkte).",
    rulesFinalFail: "• Finaler Fehlschlag: Die letzte Karte verpassen gibt dem Gegner +5 Punkte.",
    rulesKingFinish: "• King Finish: Mit der allerletzten Karte des Spiels einen Stich mit einem König machen (+5 Punkte).",
    rulesAsFinish: "• As-Finish: Mit der allerletzten Karte des Spiels einen Stich mit einem Ass machen (+5 Punkte für den Gegner).",
    announcements: {
      ronda: "Ronda! (+1) - {name}",
      tringa: "Tringa! (+5) - {name}",
      missa: "Missa! (+1) - {name}",
      derba: "Derba! (+1) - {name}",
      taawida: "Taawida! - {name}",
      counterAttackTitle: "Gegenangriff",
      counterAttackDesc: "Derba wurde gekontert",
      ultimateCounterTitle: "Ultimativer Konter",
      ultimateCounterDesc: "Ultimativer Gegenangriff",
      clash: "Clash! Beide haben Ronda!",
      clashWon: "Clash gewonnen mit {type}! (+{pts}) - {name}",
      clashDraw: "Clash Unentschieden!",
      kingFinish: "👑 King Finish! (+5)",
      tringaWins: "Tringa schlägt Ronda! (+6) - {name}",
      finalFailTitle: "Finaler Fehlschlag",
      finalFailDesc: "Letzte Karte verpasst! (+5 für den Gegner)",
      asFinishTitle: "As-Finish",
      asFinishDesc: "Mit dem Ass gewonnen! (+5 für den Gegner)"
    }
  },
  ar: {
    singleplayer: "لاعب واحد",
    playVsBot: "ابدأ اللعبة",
    onlineMultiplayer: "اللعب عبر الإنترنت",
    matchId: "رقم الغرفة",
    enterRoomId: "أدخل رقم الغرفة",
    logo: "روندا",
    host: "إنشاء",
    join: "انضمام",
    opponent: "الخصم",
    you: "أنت",
    yourTurn: "(دورك)",
    cards: "البطاقات:",
    tableEmpty: "الطاولة فارغة",
    gameOver: "انتهت اللعبة!",
    itsADraw: "تعادل!",
    youWon: "لقد فزت!",
    opponentWon: "فاز الخصم!",
    playAgain: "العب مرة أخرى",
    mainMenu: "القائمة الرئيسية",
    cardsRemaining: "البطاقات المتبقية",

    roundOver: "انتهت الجولة!",
    totalGames: "إجمالي الانتصارات",
    shareText: "انضم إلى لعبة روندا الخاصة بي!",
    linkCopied: "تم نسخ الرابط إلى الحافظة!",
    donateBtn: "اهدي الفريق كاس د أتاي بالنعناع",
    donateMsg: "عجباتك اللعبة؟ اهدي الفريق المطور كاس د أتاي!",
    connecting: "جاري الاتصال...",
    connectingDetail: "في انتظار استجابة خادم اللعبة.",
    roomOccupied: "الغرفة محجوزة، يرجى اختيار اسم آخر.",
    roomFull: "الغرفة ممتلئة.",
    backToMenu: "العودة للقائمة",
    shareLink: "نسخ رابط الدعوة",
    rulesBtn: "قواعد اللعبة",
    contactUs: "اتصل بنا",
    rulesTitle: "كيف تلعب روندا",
    rulesIntro: "روندا هي لعبة بطاقات شهيرة تُلعب بـ 40 بطاقة. الهدف هو جمع البطاقات والحصول على أكبر عدد من النقاط.",
    rulesGameplay: "طريقة اللعب: يحصل كل لاعب على 3 بطاقات في كل جولة. العب بطاقة واحدة في كل دور. إذا تطابقت بطاقتك مع بطاقة على الطاولة، فإنك تأخذها مع أي بطاقات تليها بالتسلسل.",
    rulesPoints: "النقاط: اللاعب الذي يجمع أكبر عدد من البطاقات يفوز بالجولة. الحركات الخاصة تعطي نقاط إضافية:",
    rulesMissa: "• ميسة: أخذ جميع البطاقات من الطاولة (+1 نقطة).",
    rulesDerba: "• ضربة: أخذ نفس البطاقة التي لعبها الخصم للتو (+1 نقطة).",
    rulesRonda: "• روندا: الحصول على زوج من البطاقات المتطابقة في اليد (+1 نقطة).",
    rulesTringa: "• ترينجا: الحصول على ثلاث بطاقات متطابقة في اليد (+5 نقاط).",
    rulesSpecialMovesTitle: "أحداث خاصة",
    rulesClash: "• تصادم الروندات: إذا كان لدى كلا اللاعبين روندا، فإن الزوج الأعلى يفوز (+2 نقاط).",
    rulesTringaVsRonda: "• ترينجا ضد روندا: ترينجا تتغلب على روندا وتفوز بجميع النقاط (+6).",
    rulesTringaVsTringa: "• ترينجا ضد ترينجا: إذا كان لدى كلا اللاعبين ترينجا، فإن الرتبة الأعلى تفوز (+10 نقاط).",
    rulesCounterAttack: "• هجوم مضاد: الرد على ضربة (تعويدة) (+5 نقاط).",
    rulesUltimateAttack: "• هجوم نهائي: الرد على الهجوم المضاد (+10 نقاط).",
    rulesFinalFail: "• القاعة مشات: تفويت البطاقة الأخيرة يعطي الخصم +5 نقاط.",
    rulesKingFinish: "• القاعة بالراي: الربح بالملك في آخر ورقة في اللعبة (+5 نقاط).",
    rulesAsFinish: "• القاعة باللاص: الربح بالآص في آخر ورقة في اللعبة يعطي الخصم +5 نقاط.",
    announcements: {
      ronda: "روندا (+1) - {name}",
      tringa: "ترينجا (+5) - {name}",
      missa: "ميسة (+1) - {name}",
      derba: "ضربة (+1) - {name}",
      taawida: "تعويدة - {name}",
      counterAttackTitle: "هجوم مضاد",
      counterAttackDesc: "تم صد الضربة",
      ultimateCounterTitle: "صد نهائي",
      ultimateCounterDesc: "هجوم مضاد نهائي",
      clash: "إصطدام الروندات",
      clashWon: "فوز في التصادم بـ {type}! (+{pts}) - {name}",
      clashDraw: "تعادل في التصادم",
      kingFinish: "👑 القاعة بالراي! (+5)",
      tringaWins: "ترينجا تغلب روندا! (+6) - {name}",
      finalFailTitle: "القاعة مشات",
      finalFailDesc: "فشل في الورقة الأخيرة! (+5 للخصم)",
      asFinishTitle: "القاعة باللاص",
      asFinishDesc: "ربح بالآص في الأخير! (+5 للخصم)"
    }
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('ronda-lang') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('ronda-lang', lang);
  };

  const t = (key, params = {}) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value[k] === undefined) return key;
      value = value[k];
    }

    if (typeof value === 'string' && Object.keys(params).length > 0) {
      return Object.keys(params).reduce((str, paramKey) => {
        return str.replace(`{${paramKey}}`, params[paramKey]);
      }, value);
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
