/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useContext } from 'react';

export const translations = {
  en: {
    singleplayer: "Singleplayer",
    playVsBot: "Start Game",
    onlineMultiplayer: "Online Multiplayer",
    matchId: "Match ID",
    enterRoomId: "Enter Room ID",
    logo: "RONDA",
    host: "Host",
    join: "Join",
    opponent: "Opponent",
    you: "You",
    yourTurn: "(Your Turn)",
    cards: "Cards:",
    tableEmpty: "Table is empty",
    gameOver: "Game Over!",
    itsADraw: "It's a draw!",
    youWon: "You won!",
    youLost: "You lost!",
    playAgain: "Play Again",
    mainMenu: "Main Menu",
    cardsRemaining: "Cards remaining",
    rematchMotivation: "Don't give up! Time for a rematch!",
    adLoading: "Loading Advertisement...",

    roundOver: "Round Over!",
    totalGames: "Total Wins",
    shareText: "Join my Ronda game!",
    linkCopied: "Link copied to clipboard!",
    donateBtn: "Buy us a Mint Tea",
    donateMsg: "Enjoying the game? Buy the dev team a cup of Mint Tea!",
    connecting: "Connecting...",
    connectingDetail: "Waiting for the game server to respond.",
    roomOccupied: "Room is occupied, please choose another name.",
    roomFull: "Room is full.",
    createRoom: "Create Room",
    joinRoom: "Join Room",
    yourNickname: "Your Nickname",
    enterNickname: "Enter name",
    roomPrivacy: "Room Privacy",
    public: "Public",
    private: "Private",
    cancel: "Cancel",
    back: "Back",
    create: "Create",
    publicRooms: "Public Rooms",
    privateRoom: "Private Room",
    refresh: "Refresh",
    openRooms: "Open Rooms",
    searchingRooms: "Searching for rooms...",
    noRoomsFound: "No open rooms found. Create your own!",
    enterNameError: "Please enter a name.",
    createRoomError: "Room already exists or server is offline. Please choose a different ID.",
    roomNotFoundError: "Room not found.",
    roomFullError: "Room is already full.",
    joinError: "Room not found or error joining.",
    fetchRoomsError: "Failed to retrieve public rooms.",
    hostLeftError: "The host has left the room.",
    backToMenu: "Back to Menu",
    shareLink: "Copy Invitation Link",
    rulesBtn: "How to Play",
    contactUs: "Contact us",
    rulesTitle: "How to Play Ronda",
    rulesIntro: "Ronda is a popular card game played with a 40-card deck. The goal is to capture cards and accumulate the most points.",
    rulesGameplay: "Gameplay: Players receive 3 cards per round. Play one card per turn. If your card matches a card on the table, you capture it along with any following cards in sequence.",
    rulesPoints: "Scoring: The player with the most captured cards wins the round. Special moves give immediate bonus points:",
    rulesMissa: "• Missa: Clearing all cards from the table (+1 point).",
    rulesDerba: "• Derba (hit): Capturing the exact card the opponent just played (+1 point).",
    rulesRonda: "• Ronda: Having a pair in hand after cards are dealt (+1 point).",
    rulesTringa: "• Tringa: Having three of a kind in hand (+5 points).",
    rulesSpecialMovesTitle: "Special Events",
    rulesClash: "• Clash of Rondas: If both players have Ronda, the higher pair wins all points (+2).",
    rulesTringaVsRonda: "• Tringa vs Ronda: Tringa beats Ronda and wins all points (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa: If both players have Tringa, the higher rank wins (+10 points).",
    rulesCounterAttack: "• Counter Attack: Countering a Derba (Taawida) (+5 points).",
    rulesUltimateAttack: "• Ultimate Attack: Countering a Counter Attack (+10 points).",
    rulesFinalFail: "• Final Fail: Missing the last card gives +5 points to the opponent.",
    rulesKingFinish: "• King Finish: Capturing with a King as the very last card of the game (+5 points).",
    rulesAsFinish: "• As Finish: Capturing with an Ace as the very last card gives +5 points to the opponent.",
    announcements: {
      rondaMe: "You have a Ronda (+1 you)",
      rondaOpponent: "{oppName} has a Ronda (+1 {oppName})",
      tringaMe: "You have a Tringa (+5 you)",
      tringaOpponent: "{oppName} has a Tringa (+5 {oppName})",
      missaMe: "You cleared the table (+1 you)",
      missaOpponent: "{oppName} has cleared the table (+1 {oppName})",
      derbaMe: "You hit {oppName} (+1 you)",
      derbaOpponent: "{oppName} hits you (+1 {oppName})",
      counterAttackTitle: "Counter Attack",
      counterAttackMe: "You countered {oppName}'s attack (+5 you)",
      counterAttackOpponent: "Your attack was countered by {oppName} (+5 {oppName})",
      ultimateCounterTitle: "Ultimate Counter",
      ultimateCounterMe: "You executed an Ultimate Counter (+10 you)",
      ultimateCounterOpponent: "{oppName} executed an Ultimate Counter (+10 {oppName})",
      clashRonda: "Both of you have Ronda. The winner will be announced at the end of the round",
      clashTringa: "Both of you have Tringa. The winner will be announced at the end of the round",
      clashWonTitle: "Clash Won",
      clashLostTitle: "Clash Lost",
      clashWonRondaMe: "You won the Clash of the Rondas (+{pts} you)",
      clashWonTringaMe: "You won the Clash of the Tringas (+{pts} you)",
      clashWonRondaOpp: "You lost the Clash of the Rondas (+{pts} {oppName})",
      clashWonTringaOpp: "You lost the Clash of the Tringas (+{pts} {oppName})",
      clashDraw: "Clash Draw!",
      kingFinishMe: "👑 King Finish! (+5 you)",
      kingFinishOpponent: "👑 King Finish! (+5 {oppName})",
      tringaWinsMe: "Your Tringa beats {oppName}'s Ronda (+6 you)",
      tringaWinsOpponent: "{oppName}'s Tringa beats your Ronda (+6 {oppName})",
      finalFailTitle: "Final Fail",
      finalFailMe: "{oppName} missed the last card! (+5 you)",
      finalFailOpponent: "You missed the last card! (+5 {oppName})",
      asFinishTitle: "As Finish",
      asFinishMe: "{oppName} captured with Ace! (+5 you)",
      asFinishOpponent: "You captured with Ace! (+5 {oppName})"
    }
  },
  fr: {
    singleplayer: "Un Joueur",
    playVsBot: "Commencer le jeu",
    onlineMultiplayer: "Multijoueur en Ligne",
    matchId: "ID du Match",
    enterRoomId: "Entrer l'ID",
    logo: "RONDA",
    host: "Créer",
    join: "Rejoindre",
    opponent: "Adversaire",
    you: "Vous",
    yourTurn: "(À ton tour)",
    cards: "Cartes :",
    tableEmpty: "La table est vide",
    gameOver: "Partie Terminée !",
    itsADraw: "Égalité !",
    youWon: "Vous avez gagné !",
    youLost: "Vous avez perdu !",
    playAgain: "Rejouer",
    mainMenu: "Menu Principal",
    cardsRemaining: "Cartes restantes",
    rematchMotivation: "N'abandonnez pas ! L'heure de la revanche a sonné !",
    adLoading: "Chargement de la publicité...",

    roundOver: "Manche Terminée !",
    totalGames: "Victoires Totales",
    shareText: "Rejoins ma partie de Ronda !",
    linkCopied: "Lien copié dans le presse-papiers !",
    donateBtn: "Offrez-nous un Thé à la Menthe",
    donateMsg: "Vous aimez le jeu ? Offrez un thé à l'équipe de développement !",
    connecting: "Connexion...",
    connectingDetail: "En attente d'une réponse du serveur de jeu.",
    roomOccupied: "La salle est occupée, veuillez choisir un autre nom.",
    roomFull: "La salle est pleine.",
    createRoom: "Créer un salon",
    joinRoom: "Rejoindre un salon",
    yourNickname: "Votre pseudo",
    enterNickname: "Entrez un pseudo",
    roomPrivacy: "Confidentialité du salon",
    public: "Public",
    private: "Privé",
    cancel: "Annuler",
    back: "Retour",
    create: "Créer",
    publicRooms: "Salons Publics",
    privateRoom: "Salon Privé",
    refresh: "Actualiser",
    openRooms: "Salons Ouverts",
    searchingRooms: "Recherche de salons...",
    noRoomsFound: "Aucun salon ouvert trouvé. Créez le vôtre !",
    enterNameError: "Veuillez entrer un nom.",
    createRoomError: "Le salon existe déjà ou le serveur est hors ligne. Veuillez choisir un autre ID.",
    roomNotFoundError: "Salon non trouvé.",
    roomFullError: "Le salon est déjà plein.",
    joinError: "Salon non trouvé ou erreur de connexion.",
    fetchRoomsError: "Échec de la récupération des salons publics.",
    hostLeftError: "L'hôte a quitté le salon.",
    backToMenu: "Retour au Menu",
    shareLink: "Copier le lien d'invitation",
    rulesBtn: "Règles du jeu",
    contactUs: "Nous contacter",
    rulesTitle: "Comment jouer à Ronda",
    rulesIntro: "Ronda est un jeu de cartes populaire joué avec un jeu de 40 cartes. Le but est de capturer des cartes et d'accumuler le plus de points.",
    rulesGameplay: "Déroulement : Les joueurs reçoivent 3 cartes par manche. Jouez une carte par tour. Si votre carte correspond à une carte sur la table, vous la capturez avec les cartes suivantes en séquence.",
    rulesPoints: "Points : Le joueur avec le plus de cartes capturées gagne. Les coups spéciaux donnent des points bonus immédiats :",
    rulesMissa: "• Missa : Vider toutes les cartes de la table (+1 point).",
    rulesDerba: "• Derba (frappe) : Capturer la carte exacte que l'adversaire vient de jouer (+1 point).",
    rulesRonda: "• Ronda : Avoir une paire en main après la distribution (+1 point).",
    rulesTringa: "• Tringa : Avoir un brelan en main (+5 points).",
    rulesSpecialMovesTitle: "Événements Spéciaux",
    rulesClash: "• Clash de Rondas : Si les deux joueurs ont Ronda, la paire la plus haute gagne (+2 points).",
    rulesTringaVsRonda: "• Tringa vs Ronda : Tringa bat Ronda et gagne tous les points (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa : Si les deux joueurs ont Tringa, le plus haut gagne (+10 points).",
    rulesCounterAttack: "• Contre-Attaque : Contrer une Derba (Taawida) (+5 points).",
    rulesUltimateAttack: "• Attaque Ultime : Contrer une Contre-Attaque (+10 points).",
    rulesFinalFail: "• Échec Final : Rater la dernière carte donne +5 points à l'adversaire.",
    rulesKingFinish: "• King Finish : Faire un pli avec un Roi comme toute dernière carte du jeu (+5 points).",
    rulesAsFinish: "• As Finish : Faire un pli avec un As comme toute dernière carte donne +5 points à l'adversaire.",
    announcements: {
      rondaMe: "Vous avez une Ronda (+1 vous)",
      rondaOpponent: "{oppName} a une Ronda (+1 {oppName})",
      tringaMe: "Vous avez une Tringa (+5 vous)",
      tringaOpponent: "{oppName} a une Tringa (+5 {oppName})",
      missaMe: "Vous avez nettoyé la table (+1 vous)",
      missaOpponent: "{oppName} a nettoyé la table (+1 {oppName})",
      derbaMe: "Vous avez frappé {oppName} (+1 vous)",
      derbaOpponent: "{oppName} vous a frappé (+1 {oppName})",
      counterAttackTitle: "Contre-Attaque",
      counterAttackMe: "Vous avez contré l'attaque de {oppName} (+5 vous)",
      counterAttackOpponent: "Votre attaque a été contrée par {oppName} (+5 {oppName})",
      ultimateCounterTitle: "Contre Ultime",
      ultimateCounterMe: "Vous avez exécuté un Contre Ultime (+10 vous)",
      ultimateCounterOpponent: "{oppName} a exécuté un Contre Ultime (+10 {oppName})",
      clashRonda: "Vous avez tous les deux Ronda. Le gagnant sera annoncé à la fin de la manche",
      clashTringa: "Vous avez tous les deux Tringa. Le gagnant sera annoncé à la fin de la manche",
      clashWonTitle: "Clash Gagné",
      clashLostTitle: "Clash Perdu",
      clashWonRondaMe: "Vous avez gagné le Clash des Rondas (+{pts} vous)",
      clashWonTringaMe: "Vous avez gagné le Clash des Tringas (+{pts} vous)",
      clashWonRondaOpp: "Vous avez perdu le Clash des Rondas (+{pts} {oppName})",
      clashWonTringaOpp: "Vous avez perdu le Clash des Tringas (+{pts} {oppName})",
      clashDraw: "Clash : Égalité !",
      kingFinishMe: "👑 King Finish ! (+5 vous)",
      kingFinishOpponent: "👑 King Finish ! (+5 {oppName})",
      tringaWinsMe: "Votre Tringa bat la Ronda de {oppName} (+6 vous)",
      tringaWinsOpponent: "La Tringa de {oppName} bat votre Ronda (+6 {oppName})",
      finalFailTitle: "Échec Final",
      finalFailMe: "{oppName} a manqué la dernière carte ! (+5 vous)",
      finalFailOpponent: "Vous avez manqué la dernière carte ! (+5 {oppName})",
      asFinishTitle: "As Finish",
      asFinishMe: "{oppName} a capturé avec l'As ! (+5 vous)",
      asFinishOpponent: "Vous avez capturé avec l'As ! (+5 {oppName})"
    }
  },
  de: {
    singleplayer: "Einzelspieler",
    playVsBot: "Spiel starten",
    onlineMultiplayer: "Online-Mehrspieler",
    matchId: "Match-ID",
    enterRoomId: "Raum-ID eingeben",
    logo: "RONDA",
    host: "Erstellen",
    join: "Beitreten",
    opponent: "Gegner",
    you: "Du",
    yourTurn: "(Du bist dran)",
    cards: "Karten:",
    tableEmpty: "Der Tisch ist leer",
    gameOver: "Spiel vorbei!",
    itsADraw: "Unentschieden!",
    youWon: "Du hast gewonnen!",
    youLost: "Du hast verloren!",
    playAgain: "Nochmal spielen",
    mainMenu: "Hauptmenü",
    cardsRemaining: "Verbleibende Karten",
    rematchMotivation: "Gib nicht auf! Zeit für eine Revanche!",
    adLoading: "Werbung wird geladen...",

    roundOver: "Runde vorbei!",
    totalGames: "Gesamtsiege",
    shareText: "Tritt meinem Ronda-Spiel bei!",
    linkCopied: "Link in die Zwischenablage kopiert!",
    donateBtn: "Spendier uns einen Minztee",
    donateMsg: "Gefällt dir das Spiel? Spendier dem Team einen Minztee!",
    connecting: "Verbindung wird hergestellt...",
    connectingDetail: "Warten auf Antwort vom Spielserver.",
    roomOccupied: "Raum ist besetzt, bitte wähle einen anderen Namen.",
    roomFull: "Raum ist voll.",
    createRoom: "Raum erstellen",
    joinRoom: "Raum beitreten",
    yourNickname: "Dein Name",
    enterNickname: "Namen eingeben",
    roomPrivacy: "Raum-Typ",
    public: "Öffentlich",
    private: "Privat",
    cancel: "Abbrechen",
    back: "Zurück",
    create: "Erstellen",
    publicRooms: "Öffentliche Räume",
    privateRoom: "Privater Raum",
    refresh: "Aktualisieren",
    openRooms: "Offene Räume",
    searchingRooms: "Suche nach Räumen...",
    noRoomsFound: "Keine offenen Räume gefunden. Erstelle selbst einen!",
    enterNameError: "Bitte gib einen Namen ein.",
    createRoomError: "Raum existiert bereits oder der Server ist offline. Bitte wähle eine andere ID.",
    roomNotFoundError: "Raum nicht gefunden.",
    roomFullError: "Raum ist bereits voll.",
    joinError: "Raum nicht gefunden oder Fehler beim Beitreten.",
    fetchRoomsError: "Fehler beim Abrufen der öffentlichen Räume.",
    hostLeftError: "Der Host hat den Raum verlassen.",
    backToMenu: "Zurück zum Menü",
    shareLink: "Einladungslink kopieren",
    rulesBtn: "Spielregeln",
    contactUs: "Kontaktiere uns",
    rulesTitle: "Wie man Ronda spielt",
    rulesIntro: "Ronda ist ein beliebtes Kartenspiel mit 40 Karten. Das Ziel ist es, Karten zu sammeln und die meisten Punkte zu erzielen.",
    rulesGameplay: "Spielablauf: Jeder Spieler erhält 3 Karten pro Runde. Spiele eine Karte pro Zug. Wenn deine Karte mit einer Karte auf dem Tisch übereinstimmt, nimmst du sie sowie alle nachfolgenden Karten in der Reihe.",
    rulesPoints: "Punkte: Der Spieler mit den meisten Karten gewinnt die Runde. Spezielle Züge geben sofortige Bonuspunkte:",
    rulesMissa: "• Missa: Alle Karten vom Tisch abräumen (+1 Punkt).",
    rulesDerba: "• Derba (Schlag): Genau die Karte nehmen, die der Gegner gerade gespielt hat (+1 Punkt).",
    rulesRonda: "• Ronda: Ein Paar auf der Hand haben, nachdem die Karten ausgeteilt wurden (+1 Punkt).",
    rulesTringa: "• Tringa: Drei gleiche Karten auf der Hand haben (+5 Punkte).",
    rulesSpecialMovesTitle: "Besondere Ereignisse",
    rulesClash: "• Clash of Rondas: Wenn beide Spieler Ronda haben, gewinnt das höhere Paar (+2 Punkte).",
    rulesTringaVsRonda: "• Tringa vs Ronda: Tringa schlägt Ronda und gewinnt alle Punkte (+6).",
    rulesTringaVsTringa: "• Tringa vs Tringa: Wenn beide Spieler Tringa haben, gewinnt der höhere Rang (+10 Punkte).",
    rulesCounterAttack: "• Gegenangriff: Kontern einer Derba (Taawida) (+5 Punkte).",
    rulesUltimateAttack: "• Ultimativer Konter: Kontern eines Gegenangriffs (+10 Punkte).",
    rulesFinalFail: "• Finaler Fehlschlag: Die letzte Karte verpassen gibt dem Gegner +5 Punkte.",
    rulesKingFinish: "• King Finish: Mit der allerletzten Karte des Spiels einen Stich mit einem König machen (+5 Punkte).",
    rulesAsFinish: "• As-Finish: Mit der allerletzten Karte des Spiels einen Stich mit einem Ass machen (+5 Punkte für den Gegner).",
    announcements: {
      rondaMe: "Du hast eine Ronda (+1 Sie)",
      rondaOpponent: "{oppName} hat eine Ronda (+1 {oppName})",
      tringaMe: "Du hast eine Tringa (+5 Sie)",
      tringaOpponent: "{oppName} hat eine Tringa (+5 {oppName})",
      missaMe: "Du hast den Tisch abgeräumt (+1 Sie)",
      missaOpponent: "{oppName} hat den Tisch abgeräumt (+1 {oppName})",
      derbaMe: "Du hast {oppName} getroffen (+1 Sie)",
      derbaOpponent: "{oppName} hat dich getroffen (+1 {oppName})",
      counterAttackTitle: "Gegenangriff",
      counterAttackMe: "Du hast den Angriff von {oppName} gekontert (+5 Sie)",
      counterAttackOpponent: "Dein Angriff wurde von {oppName} gekontert (+5 {oppName})",
      ultimateCounterTitle: "Ultimativer Konter",
      ultimateCounterMe: "Du hast einen ultimativen Konter ausgeführt (+10 Sie)",
      ultimateCounterOpponent: "{oppName} hat einen ultimativen Konter ausgeführt (+10 {oppName})",
      clashRonda: "Ihr habt beide Ronda. Der Gewinner wird am Ende der Runde bekannt gegeben",
      clashTringa: "Ihr habt beide Tringa. Der Gewinner wird am Ende der Runde bekannt gegeben",
      clashWonTitle: "Clash gewonnen",
      clashLostTitle: "Clash verloren",
      clashWonRondaMe: "Du hast den Clash der Rondas gewonnen (+{pts} Sie)",
      clashWonTringaMe: "Du hast den Clash der Tringas gewonnen (+{pts} Sie)",
      clashWonRondaOpp: "Du hast den Clash der Rondas verloren (+{pts} {oppName})",
      clashWonTringaOpp: "Du hast den Clash der Tringas verloren (+{pts} {oppName})",
      clashDraw: "Clash Unentschieden!",
      kingFinishMe: "👑 King Finish! (+5 Sie)",
      kingFinishOpponent: "👑 King Finish! (+5 {oppName})",
      tringaWinsMe: "Deine Tringa schlägt die Ronda von {oppName} (+6 Sie)",
      tringaWinsOpponent: "Die Tringa von {oppName} schlägt deine Ronda (+6 {oppName})",
      finalFailTitle: "Finaler Fehlschlag",
      finalFailMe: "{oppName} hat die letzte Karte verpasst! (+5 Sie)",
      finalFailOpponent: "Du hast die letzte Karte verpasst! (+5 {oppName})",
      asFinishTitle: "As-Finish",
      asFinishMe: "{oppName} hat mit dem Ass gewonnen! (+5 Sie)",
      asFinishOpponent: "Du hast mit dem Ass gewonnen! (+5 {oppName})"
    }
  },
  ar: {
    singleplayer: "لاعب واحد",
    playVsBot: "ابدأ اللعبة",
    onlineMultiplayer: "اللعب عبر الإنترنت",
    matchId: "رقم الغرفة",
    enterRoomId: "أدخل رقم الغرفة",
    logo: "روندا",
    host: "إنشاء",
    join: "انضمام",
    opponent: "الخصم",
    you: "أنت",
    yourTurn: "(دورك)",
    cards: "البطاقات:",
    tableEmpty: "الطاولة فارغة",
    gameOver: "انتهت اللعبة!",
    itsADraw: "تعادل!",
    youWon: "لقد فزت!",
    youLost: "خسرتي!",
    playAgain: "العب مرة أخرى",
    mainMenu: "القائمة الرئيسية",
    cardsRemaining: "البطاقات المتبقية",
    rematchMotivation: "ما تستسلمش! واجد للطرح الجاي؟",
    adLoading: "جاري تحميل الإعلان...",

    roundOver: "انتهت الجولة!",
    totalGames: "إجمالي الانتصارات",
    shareText: "انضم إلى لعبة روندا الخاصة بي!",
    linkCopied: "تم نسخ الرابط إلى الحافظة!",
    donateBtn: "اهدي الفريق كاس د أتاي بالنعناع",
    donateMsg: "عجباتك اللعبة؟ اهدي الفريق المطور كاس د أتاي!",
    connecting: "جاري الاتصال...",
    connectingDetail: "في انتظار استجابة خادم اللعبة.",
    roomOccupied: "الغرفة محجوزة، يرجى اختيار اسم آخر.",
    roomFull: "الغرفة ممتلئة.",
    createRoom: "إنشاء غرفة",
    joinRoom: "الانضمام إلى غرفة",
    yourNickname: "اسمك المستعار",
    enterNickname: "أدخل اسمك",
    roomPrivacy: "خصوصية الغرفة",
    public: "عام",
    private: "خاص",
    cancel: "إلغاء",
    back: "رجوع",
    create: "إنشاء",
    publicRooms: "غرف عامة",
    privateRoom: "غرفة خاصة",
    refresh: "تحديث",
    openRooms: "الغرف المفتوحة",
    searchingRooms: "جاري البحث عن غرف...",
    noRoomsFound: "لم يتم العثور على غرف مفتوحة. أنشئ غرفتك الخاصة!",
    enterNameError: "يرجى إدخال اسم.",
    createRoomError: "الغرفة موجودة بالفعل أو الخادم غير متصل. يرجى اختيار اسم آخر.",
    roomNotFoundError: "الغرفة غير موجودة.",
    roomFullError: "الغرفة ممتلئة بالفعل.",
    joinError: "الغرفة غير موجودة أو حدث خطأ أثناء الانضمام.",
    fetchRoomsError: "فشل في استرداد الغرف العامة.",
    hostLeftError: "لقد غادر منشئ الغرفة.",
    backToMenu: "العودة للقائمة",
    shareLink: "نسخ رابط الدعوة",
    rulesBtn: "قواعد اللعبة",
    contactUs: "اتصل بنا",
    rulesTitle: "كيف تلعب روندا",
    rulesIntro: "روندا هي لعبة بطاقات شهيرة تُلعب بـ 40 بطاقة. الهدف هو جمع البطاقات والحصول على أكبر عدد من النقاط.",
    rulesGameplay: "طريقة اللعب: يحصل كل لاعب على 3 بطاقات في كل جولة. العب بطاقة واحدة في كل دور. إذا تطابقت بطاقتك مع بطاقة على الطاولة، فإنك تأخذها مع أي بطاقات تليها بالتسلسل.",
    rulesPoints: "النقاط: اللاعب الذي يجمع أكبر عدد من البطاقات يفوز بالجولة. الحركات الخاصة تعطي نقاط إضافية:",
    rulesMissa: "• ميسة: أخذ جميع البطاقات من الطاولة (+1 نقطة).",
    rulesDerba: "• ضربة: أخذ نفس البطاقة التي لعبها الخصم للتو (+1 نقطة).",
    rulesRonda: "• روندا: الحصول على زوج من البطاقات المتطابقة في اليد (+1 نقطة).",
    rulesTringa: "• ترينجا: الحصول على ثلاث بطاقات متطابقة في اليد (+5 نقاط).",
    rulesSpecialMovesTitle: "أحداث خاصة",
    rulesClash: "• تصادم الروندات: إذا كان لدى كلا اللاعبين روندا، فإن الزوج الأعلى يفوز (+2 نقاط).",
    rulesTringaVsRonda: "• ترينجا ضد روندا: ترينجا تتغلب على روندا وتفوز بجميع النقاط (+6).",
    rulesTringaVsTringa: "• ترينجا ضد ترينجا: إذا كان لدى كلا اللاعبين ترينجا، فإن الرتبة الأعلى تفوز (+10 نقاط).",
    rulesCounterAttack: "• هجوم مضاد: الرد على ضربة (تعويدة) (+5 نقاط).",
    rulesUltimateAttack: "• هجوم نهائي: الرد على الهجوم المضاد (+10 نقاط).",
    rulesFinalFail: "• القاعة مشات: تفويت البطاقة الأخيرة يعطي الخصم +5 نقاط.",
    rulesKingFinish: "• القاعة بالراي: الربح بالملك في آخر ورقة في اللعبة (+5 نقاط).",
    rulesAsFinish: "• القاعة باللاص: الربح بالآص في آخر ورقة في اللعبة يعطي الخصم +5 نقاط.",
    announcements: {
      rondaMe: "عندك روندا (+1 لك)",
      rondaOpponent: "{oppName} عندو روندا (+1 {oppName})",
      tringaMe: "عندك ترينجا (+5 لك)",
      tringaOpponent: "{oppName} عندو ترينجا (+5 {oppName})",
      missaMe: "مسحتي الطاولة (+1 لك)",
      missaOpponent: "{oppName} مسح الطاولة (+1 {oppName})",
      derbaMe: "ضربتي {oppName} (+1 لك)",
      derbaOpponent: "{oppName} ضربك (+1 {oppName})",
      counterAttackTitle: "هجوم مضاد",
      counterAttackMe: "رديتي الضربة لـ {oppName} (+5 لك)",
      counterAttackOpponent: "صد {oppName} ضربتك (+5 {oppName})",
      ultimateCounterTitle: "صد نهائي",
      ultimateCounterMe: "رديتي هجوم مضاد نهائي (+10 لك)",
      ultimateCounterOpponent: "الخصم رد ليك هجوم مضاد نهائي (+10 {oppName})",
      clashRonda: "بجوجكم عندكم روندا. غادي يتعرف الرابح فاللخر د الجولة",
      clashTringa: "بجوجكم عندكم ترينجا. غادي يتعرف الرابح فاللخر د الجولة",
      clashWonTitle: "فوز في التصادم",
      clashLostTitle: "خسارة في التصادم",
      clashWonRondaMe: "ربحتي إصطدام الروندات (+{pts} لك)",
      clashWonTringaMe: "ربحتي إصطدام الترينجات (+{pts} لك)",
      clashWonRondaOpp: "خسرتي إصطدام الروندات (+{pts} {oppName})",
      clashWonTringaOpp: "خسرتي إصطدام الترينجات (+{pts} {oppName})",
      clashDraw: "تعادل في التصادم",
      kingFinishMe: "👑 القاعة بالراي! (+5 لك)",
      kingFinishOpponent: "👑 القاعة بالراي! (+5 {oppName})",
      tringaWinsMe: "الترينجا ديالك غلبت الروندا د الخصم (+6 لك)",
      tringaWinsOpponent: "الترينجا د الخصم غلبت الروندا ديالك (+6 {oppName})",
      finalFailTitle: "القاعة مشات",
      finalFailMe: "الخصم زگل الورقة الأخيرة! (+5 لك)",
      finalFailOpponent: "زگلت الورقة الأخيرة! (+5 {oppName})",
      asFinishTitle: "القاعة باللاص",
      asFinishMe: "الخصم ربح بالآص في الأخير! (+5 لك)",
      asFinishOpponent: "ربحتي بالآص في الأخير! (+5 {oppName})"
    }
  }
};

const LanguageContext = createContext();

const safeGetLocalStorage = (key, fallback) => {
  try {
    return localStorage.getItem(key) || fallback;
  } catch (e) {
    console.warn('[LanguageContext] localStorage is blocked:', e);
    return fallback;
  }
};

const safeSetLocalStorage = (key, value) => {
  try {
    localStorage.setItem(key, value);
  } catch (e) {
    console.warn('[LanguageContext] localStorage is blocked:', e);
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return safeGetLocalStorage('ronda-lang', 'en');
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    safeSetLocalStorage('ronda-lang', lang);
  };

  const t = (key, params = {}) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value[k] === undefined) return key;
      value = value[k];
    }

    if (typeof value === 'string' && Object.keys(params).length > 0) {
      return Object.keys(params).reduce((str, paramKey) => {
        return str.replaceAll(`{${paramKey}}`, params[paramKey]);
      }, value);
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
